<a href="https://colab.research.google.com/github/stefdworschak/ai-business-app/blob/vectorstore-and-agent/solve_business_problems_with_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Solve Business Problems with AI

## Objective
Develop a proof-of-concept application to intelligently process email order requests and customer inquiries for a fashion store. The system should accurately categorize emails as either product inquiries or order requests and generate appropriate responses using the product catalog information and current stock status.

You are encouraged to use AI assistants (like ChatGPT or Claude) and any IDE of your choice to develop your solution. Many modern IDEs (such as PyCharm, or Cursor) can work with Jupiter files directly.

## Task Description

### Inputs

Google Spreadsheet **[Document](https://docs.google.com/spreadsheets/d/14fKHsblfqZfWj3iAaM2oA51TlYfQlFT4WKo52fVaQ9U)** containing:

- **Products**: List of products with fields including product ID, name, category, stock amount, detailed description, and season.

- **Emails**: Sequential list of emails with fields such as email ID, subject, and body.

### Instructions

- Implement all requirements using advanced Large Language Models (LLMs) to handle complex tasks, process extensive data, and generate accurate outputs effectively.
- Use Retrieval-Augmented Generation (RAG) and vector store techniques where applicable to retrieve relevant information and generate responses.
- You are provided with a temporary OpenAI API key granting access to GPT-4o, which has a token quota. Use it wisely or use your own key if preferred.
- Address the requirements in the order listed. Review them in advance to develop a general implementation plan before starting.
- Your deliverables should include:
   - Code developed within this notebook.
   - A single spreadsheet containing results, organized across separate sheets.
   - Comments detailing your thought process.
- You may use additional libraries (e.g., langchain) to streamline the solution. Use libraries appropriately to align with best practices for AI and LLM tools.
- Use the most suitable AI techniques for each task. Note that solving tasks with traditional programming methods will not earn points, as this assessment evaluates your knowledge of LLM tools and best practices.

### Requirements

#### 1. Classify emails
    
Classify each email as either a _**"product inquiry"**_ or an _**"order request"**_. Ensure that the classification accurately reflects the intent of the email.

**Output**: Populate the **email-classification** sheet with columns: email ID, category.

#### 2. Process order requests
1.   Process orders
  - For each order request, verify product availability in stock.
  - If the order can be fulfilled, create a new order line with the status “created”.
  - If the order cannot be fulfilled due to insufficient stock, create a line with the status “out of stock” and include the requested quantity.
  - Update stock levels after processing each order.
  - Record each product request from the email.
  - **Output**: Populate the **order-status** sheet with columns: email ID, product ID, quantity, status (**_"created"_**, **_"out of stock"_**).

2.   Generate responses
  - Create response emails based on the order processing results:
      - If the order is fully processed, inform the customer and provide product details.
      - If the order cannot be fulfilled or is only partially fulfilled, explain the situation, specify the out-of-stock items, and suggest alternatives or options (e.g., waiting for restock).
  - Ensure the email tone is professional and production-ready.
  - **Output**: Populate the **order-response** sheet with columns: email ID, response.

#### 3. Handle product inquiry

Customers may ask general open questions.
  - Respond to product inquiries using relevant information from the product catalog.
  - Ensure your solution scales to handle a full catalog of over 100,000 products without exceeding token limits. Avoid including the entire catalog in the prompt.
  - **Output**: Populate the **inquiry-response** sheet with columns: email ID, response.

## Evaluation Criteria
- **Advanced AI Techniques**: The system should use Retrieval-Augmented Generation (RAG) and vector store techniques to retrieve relevant information from data sources and use it to respond to customer inquiries.
- **Tone Adaptation**: The AI should adapt its tone appropriately based on the context of the customer's inquiry. Responses should be informative and enhance the customer experience.
- **Code Completeness**: All functionalities outlined in the requirements must be fully implemented and operational as described.
- **Code Quality and Clarity**: The code should be well-organized, with clear logic and a structured approach. It should be easy to understand and maintain.
- **Presence of Expected Outputs**: All specified outputs must be correctly generated and saved in the appropriate sheets of the output spreadsheet. Ensure the format of each output matches the requirements—do not add extra columns or sheets.
- **Accuracy of Outputs**: The accuracy of the generated outputs is crucial and will significantly impact the evaluation of your submission.

We look forward to seeing your solution and your approach to solving real-world problems with AI technologies.

# Prerequisites

### Configure OpenAI API Key.

In [16]:
# Install the OpenAI Python package.
%pip install openai httpx==0.27.2 langgraph==0.5.4 langchain langchain-pinecone langchain-openai langfuse

Requirement already satisfied: openai in /usr/local/lib/python3.11/dist-packages (1.97.1)
Requirement already satisfied: httpx==0.27.2 in /usr/local/lib/python3.11/dist-packages (0.27.2)
Requirement already satisfied: langgraph==0.5.4 in /usr/local/lib/python3.11/dist-packages (0.5.4)
Requirement already satisfied: langchain in /usr/local/lib/python3.11/dist-packages (0.3.26)
Requirement already satisfied: langchain-pinecone in /usr/local/lib/python3.11/dist-packages (0.2.11)
Requirement already satisfied: langchain-openai in /usr/local/lib/python3.11/dist-packages (0.3.28)
Collecting langfuse
  Downloading langfuse-3.2.1-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.11/dist-packages (from httpx==0.27.2) (4.9.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.11/dist-packages (from httpx==0.27.2) (2025.7.14)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.11/dist-packages (from httpx==0.27.2) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.11/dist-packages (from httpx==0.27.2) (3.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.11/dist-packages (from httpx==0.27.2) (1.3.1)
Requirement already satisfied: langchain-core>=0.1 in /usr/local/lib/python3.11/dist-packages (from langgraph==0.5.4) (0.3.71)
Requirement already satisfied: langgraph-checkpoint<3.0.0,>=2.1.0 in /usr/local/lib/python3.11/dist-packages (from langgraph==0.5.4) (2.1.1)
Requirement already satisfied: langgraph-prebuilt<0.6.0,>=0.5.0 in /usr/local/lib/python3.11/dist-packages (from langgraph==0.5.4) (0.5.2)
Requirement already satisfied: langgraph-sdk<0.2.0,>=0.1.42 in /usr/local/lib/python3.11/dist-packages (from langgraph==0.5.4) (0.1.74)
Requirement already satisfied: pydantic>=2.7.4 in /usr/local/lib/python3.11/dist-packages (from langgraph==0.5.4) (2.11.7)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.11/dist-packages (from langgraph==0.5.4) (3.5.0)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.11/dist-packages (from httpcore==1.*->httpx==0.27.2) (0.16.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.11/dist-packages (from openai) (1.9.0)
Requirement already satisfied: jiter<1,>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from openai) (0.10.0)
Requirement already satisfied: tqdm>4 in /usr/local/lib/python3.11/dist-packages (from openai) (4.67.1)
Requirement already satisfied: typing-extensions<5,>=4.11 in /usr/local/lib/python3.11/dist-packages (from openai) (4.14.1)
Requirement already satisfied: langchain-text-splitters<1.0.0,>=0.3.8 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.3.8)
Requirement already satisfied: langsmith>=0.1.17 in /usr/local/lib/python3.11/dist-packages (from langchain) (0.4.8)
Requirement already satisfied: SQLAlchemy<3,>=1.4 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.0.41)
Requirement already satisfied: requests<3,>=2 in /usr/local/lib/python3.11/dist-packages (from langchain) (2.32.3)
Requirement already satisfied: PyYAML>=5.3 in /usr/local/lib/python3.11/dist-packages (from langchain) (6.0.2)
Requirement already satisfied: pinecone<8.0.0,>=6.0.0 in /usr/local/lib/python3.11/dist-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (7.3.0)
Requirement already satisfied: numpy>=1.26.4 in /usr/local/lib/python3.11/dist-packages (from langchain-pinecone) (2.0.2)
Requirement already satisfied: langchain-tests<1.0.0,>=0.3.7 in /usr/local/lib/python3.11/dist-packages (from langchain-pinecone) (0.3.20)
Requirement already satisfied: tiktoken<1,>=0.7 in /usr/local/lib/python3.11/dist-packages (from langchain-openai) (0.9.0)
Collecting backoff>=1.10.0 (from langfuse)
  Downloading backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Collecting opentelemetry-api<2.0.0,>=1.33.1 (from langfuse)
  Downloading opentelemetry_api-1.35.0-py3-none-any.whl.metadata (1.5 kB)
Collecting opentelemetry-exporter-otlp<2.0.0,>=1.33.1 (from langfuse)
  Downloading opentelemetry_exporter_otlp-1.35.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-sdk<2.0.0,>=1.33.1 (from langfuse)
  Downloading opentelemetry_sdk-1.35.0-py3-none-any.whl.metadata (1.5 kB)
Requirement already satisfied: packaging<25.0,>=23.2 in /usr/local/lib/python3.11/dist-packages (from langfuse) (24.2)
Requirement already satisfied: wrapt<2.0,>=1.14 in /usr/local/lib/python3.11/dist-packages (from langfuse) (1.17.2)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.11/dist-packages (from langchain-core>=0.1->langgraph==0.5.4) (8.5.0)
Requirement already satisfied: jsonpatch<2.0,>=1.33 in /usr/local/lib/python3.11/dist-packages (from langchain-core>=0.1->langgraph==0.5.4) (1.33)
Requirement already satisfied: pytest<9,>=7 in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (8.4.1)
Requirement already satisfied: pytest-asyncio<1,>=0.20 in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (0.26.0)
Requirement already satisfied: syrupy<5,>=4 in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (4.9.1)
Requirement already satisfied: pytest-socket<1,>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (0.7.0)
Requirement already satisfied: pytest-benchmark in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (5.1.0)
Requirement already satisfied: pytest-codspeed in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (4.0.0)
Requirement already satisfied: pytest-recording in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (0.13.4)
Requirement already satisfied: vcrpy>=7.0 in /usr/local/lib/python3.11/dist-packages (from langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (7.0.0)
Requirement already satisfied: ormsgpack>=1.10.0 in /usr/local/lib/python3.11/dist-packages (from langgraph-checkpoint<3.0.0,>=2.1.0->langgraph==0.5.4) (1.10.0)
Requirement already satisfied: orjson>=3.10.1 in /usr/local/lib/python3.11/dist-packages (from langgraph-sdk<0.2.0,>=0.1.42->langgraph==0.5.4) (3.11.0)
Requirement already satisfied: requests-toolbelt<2.0.0,>=1.0.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain) (1.0.0)
Requirement already satisfied: zstandard<0.24.0,>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from langsmith>=0.1.17->langchain) (0.23.0)
Requirement already satisfied: importlib-metadata<8.8.0,>=6.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-api<2.0.0,>=1.33.1->langfuse) (8.7.0)
Collecting opentelemetry-exporter-otlp-proto-grpc==1.35.0 (from opentelemetry-exporter-otlp<2.0.0,>=1.33.1->langfuse)
  Downloading opentelemetry_exporter_otlp_proto_grpc-1.35.0-py3-none-any.whl.metadata (2.4 kB)
Collecting opentelemetry-exporter-otlp-proto-http==1.35.0 (from opentelemetry-exporter-otlp<2.0.0,>=1.33.1->langfuse)
  Downloading opentelemetry_exporter_otlp_proto_http-1.35.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: googleapis-common-protos~=1.57 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.35.0->opentelemetry-exporter-otlp<2.0.0,>=1.33.1->langfuse) (1.70.0)
Requirement already satisfied: grpcio<2.0.0,>=1.63.2 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-exporter-otlp-proto-grpc==1.35.0->opentelemetry-exporter-otlp<2.0.0,>=1.33.1->langfuse) (1.73.1)
Collecting opentelemetry-exporter-otlp-proto-common==1.35.0 (from opentelemetry-exporter-otlp-proto-grpc==1.35.0->opentelemetry-exporter-otlp<2.0.0,>=1.33.1->langfuse)
  Downloading opentelemetry_exporter_otlp_proto_common-1.35.0-py3-none-any.whl.metadata (1.8 kB)
Collecting opentelemetry-proto==1.35.0 (from opentelemetry-exporter-otlp-proto-grpc==1.35.0->opentelemetry-exporter-otlp<2.0.0,>=1.33.1->langfuse)
  Downloading opentelemetry_proto-1.35.0-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: protobuf<7.0,>=5.0 in /usr/local/lib/python3.11/dist-packages (from opentelemetry-proto==1.35.0->opentelemetry-exporter-otlp-proto-grpc==1.35.0->opentelemetry-exporter-otlp<2.0.0,>=1.33.1->langfuse) (5.29.5)
Collecting opentelemetry-semantic-conventions==0.56b0 (from opentelemetry-sdk<2.0.0,>=1.33.1->langfuse)
  Downloading opentelemetry_semantic_conventions-0.56b0-py3-none-any.whl.metadata (2.4 kB)
Requirement already satisfied: pinecone-plugin-assistant<2.0.0,>=1.6.0 in /usr/local/lib/python3.11/dist-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.7.0)
Requirement already satisfied: pinecone-plugin-interface<0.0.8,>=0.0.7 in /usr/local/lib/python3.11/dist-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.0.7)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.11/dist-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.0.post0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.11/dist-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.5.0)
Requirement already satisfied: aiohttp>=3.9.0 in /usr/local/lib/python3.11/dist-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (3.12.14)
Requirement already satisfied: aiohttp-retry<3.0.0,>=2.9.1 in /usr/local/lib/python3.11/dist-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.7.4->langgraph==0.5.4) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.7.4->langgraph==0.5.4) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.11/dist-packages (from pydantic>=2.7.4->langgraph==0.5.4) (0.4.1)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests<3,>=2->langchain) (3.4.2)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.11/dist-packages (from SQLAlchemy<3,>=1.4->langchain) (3.2.3)
Requirement already satisfied: regex>=2022.1.18 in /usr/local/lib/python3.11/dist-packages (from tiktoken<1,>=0.7->langchain-openai) (2024.11.6)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (25.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (6.6.3)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.3.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.20.1)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.11/dist-packages (from importlib-metadata<8.8.0,>=6.0->opentelemetry-api<2.0.0,>=1.33.1->langfuse) (3.23.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.11/dist-packages (from jsonpatch<2.0,>=1.33->langchain-core>=0.1->langgraph==0.5.4) (3.0.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.11/dist-packages (from pytest<9,>=7->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (2.1.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.11/dist-packages (from pytest<9,>=7->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.11/dist-packages (from pytest<9,>=7->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (2.19.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.5.3->pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.17.0)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from pytest-benchmark->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (9.0.0)
Requirement already satisfied: cffi>=1.17.1 in /usr/local/lib/python3.11/dist-packages (from pytest-codspeed->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (1.17.1)
Requirement already satisfied: rich>=13.8.1 in /usr/local/lib/python3.11/dist-packages (from pytest-codspeed->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (13.9.4)
Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.17.1->pytest-codspeed->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (2.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.11/dist-packages (from rich>=13.8.1->pytest-codspeed->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (3.0.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.11/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.1->pytest-codspeed->langchain-tests<1.0.0,>=0.3.7->langchain-pinecone) (0.1.2)
Downloading langfuse-3.2.1-py3-none-any.whl (299 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 299.3/299.3 kB 10.7 MB/s eta 0:00:00
Downloading backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading opentelemetry_api-1.35.0-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.6/65.6 kB 6.2 MB/s eta 0:00:00
Downloading opentelemetry_exporter_otlp-1.35.0-py3-none-any.whl (7.0 kB)
Downloading opentelemetry_exporter_otlp_proto_grpc-1.35.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_exporter_otlp_proto_http-1.35.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_exporter_otlp_proto_common-1.35.0-py3-none-any.whl (18 kB)
Downloading opentelemetry_proto-1.35.0-py3-none-any.whl (72 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.5/72.5 kB 7.2 MB/s eta 0:00:00
Downloading opentelemetry_sdk-1.35.0-py3-none-any.whl (119 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.4/119.4 kB 10.8 MB/s eta 0:00:00
Downloading opentelemetry_semantic_conventions-0.56b0-py3-none-any.whl (201 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.6/201.6 kB 17.7 MB/s eta 0:00:00
Installing collected packages: opentelemetry-proto, backoff, opentelemetry-exporter-otlp-proto-common, opentelemetry-api, opentelemetry-semantic-conventions, opentelemetry-sdk, opentelemetry-exporter-otlp-proto-http, opentelemetry-exporter-otlp-proto-grpc, opentelemetry-exporter-otlp, langfuse
Successfully installed backoff-2.2.1 langfuse-3.2.1 opentelemetry-api-1.35.0 opentelemetry-exporter-otlp-1.35.0 opentelemetry-exporter-otlp-proto-common-1.35.0 opentelemetry-exporter-otlp-proto-grpc-1.35.0 opentelemetry-exporter-otlp-proto-http-1.35.0 opentelemetry-proto-1.35.0 opentelemetry-sdk-1.35.0 opentelemetry-semantic-conventions-0.56b0

In [4]:
# Import secrets
from google.colab import userdata
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
OPENAI_BASE = userdata.get('OPENAI_BASE')
PINECONE_API_KEY = userdata.get('PINECONE_API_KEY')
LANGFUSE_PUBLIC_KEY = userdata.get('LANGFUSE_PUBLIC_KEY')
LANGFUSE_SECRET_KEY = userdata.get('LANGFUSE_SECRET_KEY')
LANGFUSE_HOST='https://cloud.langfuse.com'

In [2]:
# Code example of reading input data

import pandas as pd
from IPython.display import display

def read_data_frame(document_id, sheet_name):
    export_link = f"https://docs.google.com/spreadsheets/d/{document_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"
    return  pd.read_csv(export_link)

document_id = '14fKHsblfqZfWj3iAaM2oA51TlYfQlFT4WKo52fVaQ9U'
products_df = read_data_frame(document_id, 'products')
emails_df = read_data_frame(document_id, 'emails')

# Display first 3 rows of each DataFrame
display(products_df.head(3))
display(emails_df.head(3))

,product_id,name,category,description,stock,seasons,price
0,RSG8901,Retro Sunglasses,Accessories,Transport yourself back in time with our retro...,1,"Spring, Summer",26.99
1,SWL2345,Sleek Wallet,Accessories,Keep your essentials organized and secure with...,5,All seasons,30.00
2,VSC6789,Versatile Scarf,Accessories,Add a touch of versatility to your wardrobe wi...,6,"Spring, Fall",23.00

,email_id,subject,message
0,E001,Leather Wallets,"Hi there, I want to order all the remaining LT..."
1,E002,Buy Vibrant Tote with noise,"Good morning, I'm looking to buy the VBT2345 V..."
2,E003,Need your help,"Hello, I need a new bag to carry my laptop and..."

In [5]:
# Code example of generating output document

# Creates a new shared Google Worksheet every invocation with the proper structure
# Note: This code should be executed from the google colab once you are ready, it will not work locally
from google.colab import auth
import gspread
from google.auth import default
from gspread_dataframe import set_with_dataframe

# IMPORTANT: You need to authenticate the user to be able to create new worksheet
# Insert the authentication snippet from the official documentation to create a google client:
# https://colab.research.google.com/notebooks/io.ipynb#scrollTo=qzi9VsEqzI-o
# Authenticate user
auth.authenticate_user()
creds, _ = default()

gc = gspread.authorize(creds)

# This code goes after creating google client
output_document = gc.create('Solving Business Problems with AI - Output')

# Create 'email-classification' sheet
email_classification_sheet = output_document.add_worksheet(title="email-classification", rows=50, cols=2)
email_classification_sheet.update([['email ID', 'category']], 'A1:B1')

# Example of writing the data into the sheet
# Assuming you have your classification in the email_classification_df DataFrame
# set_with_dataframe(email_classification_sheet, email_classification_df)
# Or directly update cells: https://docs.gspread.org/en/latest/user-guide.html#updating-cells

# Create 'order-status' sheet
order_status_sheet = output_document.add_worksheet(title="order-status", rows=50, cols=4)
order_status_sheet.update([['email ID', 'product ID', 'quantity', 'status']], 'A1:D1')

# Create 'order-response' sheet
order_response_sheet = output_document.add_worksheet(title="order-response", rows=50, cols=2)
order_response_sheet.update([['email ID', 'response']], 'A1:B1')

# Create 'inquiry-response' sheet
inquiry_response_sheet = output_document.add_worksheet(title="inquiry-response", rows=50, cols=2)
inquiry_response_sheet.update([['email ID', 'response']], 'A1:B1')

# Share the spreadsheet publicly
output_document.share('', perm_type='anyone', role='reader')

# This is the solution output link, paste it into the submission form
print(f"Shareable link: https://docs.google.com/spreadsheets/d/{output_document.id}")

Shareable link: https://docs.google.com/spreadsheets/d/1Ce4M4urMD4aFiraDHwh3D-yr6RVDXQj1bNpufDWcwsE

In [6]:
# Create VectorstoreFactory
from uuid import uuid4

from langchain_core.documents import Document
from langchain_openai import OpenAIEmbeddings
from langchain_pinecone import PineconeVectorStore
from langchain.text_splitter import RecursiveCharacterTextSplitter

from pinecone import Pinecone, ServerlessSpec


class VectorstoreFactory:
    def __init__(self, pinecone):
        self.pinecone = pinecone
        self.index = None
        self.embeddings = None
        self.vector_store = None

    def get_or_create_index(self, index_name, dimension=768):
        if not self.pinecone.has_index(index_name):
            self.pinecone.create_index(
                name=index_name,
                dimension=1536,
                metric="cosine",
                spec=ServerlessSpec(cloud="aws", region="us-east-1"),
            )

        self.index = self.pinecone.Index(index_name)
        return self.index

    def get_embeddings(self):
        self.embeddings = OpenAIEmbeddings(
            model='text-embedding-3-small',
            openai_api_key=OPENAI_API_KEY,
            openai_api_base=OPENAI_BASE,
        )
        return self.embeddings

    def get_vectorstore(self, index_name):
        self.vector_store =  PineconeVectorStore(
            index=self.get_or_create_index(index_name),
            embedding=self.get_embeddings())
        return self.vector_store

    def create_document(self, page_content, metadata={}):
        return Document(
            page_content=page_content,
            metadata=metadata
        )

    def chunk_text(self, text, chunk_size=500, chunk_overlap=50):
        """Chunk text into smaller pieces for better embedding performance."""
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=chunk_size,
            chunk_overlap=chunk_overlap,
            length_function=len,
            separators=["\n\n", "\n", ". ", " ", ""]
        )
        return text_splitter.split_text(text)

    def create_chunked_documents(self, text, metadata={}, chunk_size=500, chunk_overlap=50):
        """Create multiple documents from chunked text."""
        chunks = self.chunk_text(text, chunk_size, chunk_overlap)
        documents = []

        for i, chunk in enumerate(chunks):
            chunk_metadata = metadata.copy()
            chunk_metadata['chunk_id'] = i
            chunk_metadata['total_chunks'] = len(chunks)
            documents.append(self.create_document(chunk, chunk_metadata))

        return documents

    def add_documents(self, documents, index_name):
        uuids = [str(uuid4()) for _ in range(len(documents))]
        self.vector_store.add_documents(documents=documents, ids=uuids)

In [8]:
from pinecone import Pinecone

index_name = 'product-store'
# Recreate the vectorstore factory with fresh instance
pinecone = Pinecone(api_key=PINECONE_API_KEY)
vectorstore_factory = VectorstoreFactory(pinecone=pinecone)
vectorstore = vectorstore_factory.get_vectorstore(index_name=index_name)

print("Vectorstore factory recreated successfully!")

Vectorstore factory recreated successfully!

In [12]:
# Storing product info in the vectorstore
documents = []
for _, row in products_df.iterrows():
    product_metadata = {
        'product_id': row['product_id'],
        'name': row['name'],
        'category': row['category'],
        'price': row['price'],
        'seasons': row['seasons'],
    }
    documents.append(vectorstore_factory.create_document(page_content=row['description'], metadata=product_metadata))
vectorstore_factory.add_documents(documents, index_name)

In [38]:
# Create StockManager including agent tool
from langchain.tools import tool
from langchain.tools import StructuredTool
from pydantic import BaseModel, Field
from typing import List


class StockManager:
    def __init__(self, stock_count: dict):
        # Consider making a copy to prevent external modifications
        self.stock_count = stock_count.copy()

    def get_stock_count(self, product_ids: List[str]) -> dict:
        """ Get the number of items left in stock for a list of products based on their product_ids. """
        return {product_id: self.stock_count.get(product_id, 0) for product_id in product_ids}

    def create_stock_count_tool(self):
        """Create a LangChain tool for getting stock counts."""

        class StockCountInput(BaseModel):
            product_ids: List[str] = Field(description="List of product IDs to check stock for")

        def stock_count_func(product_ids: List[str]) -> dict:
            """Get the number of items left in stock for a list of products based on their product_ids."""
            return self.get_stock_count(product_ids)

        return StructuredTool.from_function(
            func=stock_count_func,
            name="get_stock_count",
            description="Get the number of items left in stock for a list of products based on their product_ids",
            args_schema=StockCountInput
        )

    def update_stock(self, product_id: str, new_count: int) -> None:
        """Update stock count for a product."""
        self.stock_count[product_id] = new_count

In [17]:
# Creating a CallbackHandler for Langfuse for monitoring
from langfuse import Langfuse
from langfuse.langchain import CallbackHandler

def create_langfuse_handler(langfuse_public_key, langfuse_secret_key, langfuse_host):
    if langfuse_public_key and langfuse_secret_key and langfuse_host:
        langfuse = Langfuse(
            public_key=langfuse_public_key,
            secret_key=langfuse_secret_key,
            host=langfuse_host,
        )
        return CallbackHandler()
    return

In [19]:
# Creating our OrderAgent which handles classifying emails, processing order requests and answering order and product inquiry emails
import re
import json
from urllib import response
from langgraph.graph import StateGraph, END
from langgraph.prebuilt import ToolNode, tools_condition
from langchain.schema.runnable import Runnable
from langchain_core.runnables import RunnableLambda
from langchain_core.tools import tool
from langchain_core.documents import Document
from langchain_openai import ChatOpenAI
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage, ToolMessage
from pydantic import BaseModel
from typing import List, Literal, TypedDict, Annotated


class AgentState(TypedDict):
    email_id: str
    email_content: str
    docs: Annotated[List[Document], "retrieved documents"]
    messages: Annotated[List[AIMessage], "chat history"]
    order_analysis: Annotated[dict, "final structured output"]
    email_response: Annotated[str, "generated email response"]
    email_type: Annotated[Literal["order request", "product inquiry"], "type of email being processed"]


class OrderItem(BaseModel):
    """Schema for individual order items"""
    product_mentioned: str    # Product name/description mentioned by customer
    product_id: str          # Matched product ID from catalog
    order_quantity: int            # Quantity requested
    status: Literal["created", "out of stock"]


class OrderAnalysis(BaseModel):
    """Schema for analyzing order requests"""
    order_items: List[OrderItem]  # List of ordered items
    customer_intent: str          # What the customer wants to do
    urgency_level: Literal["low", "medium", "high"]


class OrderAgent:
    def __init__(self, llm, vector_store, stock_manager, langfuse_handler=None):
        self.llm = llm
        self.vector_store = vector_store
        self.stock_manager = stock_manager
        self.langfuse_handler = langfuse_handler

        self._build_graph()

    def create_tools(self):
        # Use the structured tool from stock manager
        return [self.stock_manager.create_stock_count_tool()]

    def should_continue_after_retrieve(self, state: AgentState) -> str:
        """Route based on email type after classification and retrieval."""
        email_type = state.get("email_type", "")

        if email_type == "order request":
            return "agent"
        elif email_type == "product inquiry":
            return "product_inquiry_response"
        else:
            # Default to order processing if unclear
            return "agent"

    def should_continue(self, state: AgentState) -> str:
        """Determine if we should continue to tools or go to analyse_order_node."""
        messages = state.get("messages", [])
        if not messages:
            return "analyse_order_node"

        last_message = messages[-1]
        # Check if the last message has tool calls
        if hasattr(last_message, 'tool_calls') and last_message.tool_calls:
            # Standard ool_calls, going to tools
            return "tools"
        elif hasattr(last_message, 'additional_kwargs') and last_message.additional_kwargs.get('function_call'):
            # Found function_call in additional_kwargs, going to tools
            return "tools"
        elif hasattr(last_message, 'additional_kwargs') and last_message.additional_kwargs.get('tool_calls'):
            # Found tool_calls in additional_kwargs, going to tools
            return "tools"
        else:
            # No tool calls found, going to analyse_order_node
            return "analyse_order_node"

    def classify_email_node(self, state: AgentState) -> AgentState:
        """Classify whether the email is an order request or product inquiry."""
        email_content = state["email_content"]

        classification_prompt = f"""
        Classify this email as either an "order request" or "product inquiry".

        Order request: Customer wants to purchase specific items, mentions quantities, expresses intent to buy
        Product inquiry: Customer is asking questions about products, wants information, recommendations, or general assistance

        Email: {email_content}

        Respond with only: "order request" or "product inquiry"
        """

        response = self.llm.invoke([HumanMessage(content=classification_prompt)])
        email_type = response.content.strip().lower()

        return {**state, "email_type": email_type}

    def retrieve_node(self, state: AgentState) -> AgentState:
        """Retrieve relevant documents based on the email content."""
        retriever = self.vector_store.as_retriever(
            search_type="similarity",
            search_kwargs={"k": 5}
        )
        email_content = state["email_content"]
        retrieved_docs = retriever.invoke(email_content)
        return {'docs': retrieved_docs, 'messages': []}

    def _create_context_from_docs(self, docs: List[Document]) -> str:
        context_parts = []
        for doc in docs:
            metadata = doc.metadata
            context_part = f"""
Product ID: {metadata.get('product_id', 'N/A')}
Name: {metadata.get('name', 'N/A')}
Category: {metadata.get('category', 'N/A')}
Seasons: {metadata.get('seasons', 'N/A')}
Description: {doc.page_content}
Price: {metadata.get('price', 'N/A')}
---"""
            context_parts.append(context_part)
        return "\n".join(context_parts)

    def agent_node(self, state: AgentState) -> AgentState:
        """Identify products and call tools to get stock information."""
        retrieved_context = self._create_context_from_docs(state["docs"])
        prompt = """
        You are analyzing an order email. Your ONLY job is to:
        1. Identify product IDs mentioned in the email or match products to IDs from the catalog
        2. Call the get_stock_count tool to get current stock levels

        Email: {email_content}

        Product catalog:
        {retrieved_context}

        Find the product IDs that the customer wants to order and call get_stock_count with those IDs.
        You MUST call the get_stock_count tool - do not just analyze, actually make the function call.
        """

        tools = self.create_tools()

        try:
            llm_with_tools = self.llm.bind_tools(tools, tool_choice="auto")
        except Exception as e:
            print(f"Error binding tools with tool_choice: {e}")
            llm_with_tools = self.llm.bind_tools(tools)

        messages = [
            HumanMessage(content=prompt.format(
                retrieved_context=retrieved_context,
                email_content=state["email_content"]))
        ]

        print(f"Calling LLM with {len(tools)} tools bound")
        response = llm_with_tools.invoke(messages)
        print(f"LLM Response type: {type(response)}")

        return {**state, "messages": state.get("messages", []) + [response]}

    def analyse_order_node(self, state: AgentState) -> AgentState:
        """Generate the OrderAnalysis using all gathered information."""

        # Extract information from the state
        email_content = state["email_content"]
        retrieved_context = self._create_context_from_docs(state["docs"])

        # Find tool results from the messages
        tool_message = state['messages'][-1].content

        # Create a comprehensive prompt with all information
        comprehensive_prompt = f"""
        Analyze this order email and create a structured OrderAnalysis.

        EMAIL:
        {email_content}

        PRODUCT CATALOG:
        {retrieved_context}

        STOCK INFORMATION:
        {tool_message if tool_message else "No stock information available"}

        Create an OrderAnalysis with:
        - order_items: List of OrderItem objects for each product the customer wants
        - customer_intent: Overall description of what the customer wants
        - urgency_level: Based on the language used (low/medium/high)

        For each OrderItem include:
        - product_mentioned: Exact product name/description the customer used
        - product_id: Matching product ID from catalog
        - order_quantity: Number of items (if customer wants "all remaining", use the stock count)
        - status: "created" if there's enough stock, "out of stock" if not enough stock

        Use the stock information above to determine quantities and status.
        Use the following format for the OrderAnalysis:

        ```json
        {{
            "order_items": [
                {{"product_id": "LTH0976", "product_mentioned": "Leather Bifold Wallets", "order_quantity": 1, "status": "created"}},
                {{"product_id": "LTH0977", "product_mentioned": "Leather Bifold Wallets", "order_quantity": 0, "status": "out of stock"}}
            ],
            "customer_intent": "The customer wants to order 1 LTH0976 Leather Bifold Wallets and 0 LTH0977 Leather Bifold Wallets",
            "urgency_level": "medium"
        }}
        ```"""

        # Use structured output with a single comprehensive message
        order_analysis_message = self.llm.invoke([
            HumanMessage(content=comprehensive_prompt)
        ])
        order_analysis = json.loads(re.search(r'```json\s*(\{.*\})\s*```', order_analysis_message.content, re.DOTALL).group(1))

        return {**state, "order_analysis": order_analysis}

    def product_inquiry_response_node(self, state: AgentState) -> AgentState:
        """Generate a response for product inquiries using retrieved context."""
        email_content = state["email_content"]
        retrieved_context = self._create_context_from_docs(state["docs"])
        print(retrieved_context)

        inquiry_response_prompt = f"""
        You are a helpful customer service assistant for a fashion store. A customer has sent a product inquiry.

        CUSTOMER EMAIL:
        {email_content}

        RELEVANT PRODUCTS FROM CATALOG:
        {retrieved_context}

        Create a helpful and professional email response that:
        - Addresses the customer's specific questions or needs
        - Provides relevant product information from the catalog
          - Use the most relevant products from the catalog to answer their questions
          - The first products should be the most relevant to the inquiry
        - If the customer does not mention a specific product name, recommend products based on their inquiry (no need to apologise in this instance)
        - Includes product details like names, descriptions, categories, and seasonal availability or prices
        - Offers helpful suggestions or recommendations
        - Maintains a friendly and professional tone
        - Offers to help with an order if the customer is interested
        - Encourages further engagement or questions

        If the customer asks about specific products, focus on those. If they ask general questions, provide helpful information based on the most relevant products from the catalog.

        Format the response as a complete email ready to send to the customer, including:
        - Professional subject line
        - Proper greeting
        - Detailed response to their inquiry
        - Product recommendations if appropriate
        - Invitation for follow-up questions
        - Professional closing

        Here are some examples of how to respond:

        Example 1:
        Customer: "Hi, I'm looking for a red scarf. Do you have any available?"
        Response: "Hello! Yes, we have a beautiful red velcrow scarf available. It's perfect for autumn and is made from soft materials. You can find it in our catalog under the name 'Red scarf'. If you're interested, I can provide more details or help you place an order.
        Let me know if you have any other questions or if there's anything else I can assist you with!"

        Example 2:
        Customer: "I would like to know more about product LTH0976 Leather Bifold Wallets. Could you tell me about it?"
        Response: "Hello! The LTH0976 Leather Bifold Wallets is a high-quality leather wallet that is both stylish and functional. It features multiple card slots, a coin pocket, and a sleek design. It's perfect for everyday use or as a gift. You can find it in our catalog under the name 'Leather Bifold Wallets'. If you have any specific questions or need more details, feel free to ask!"
        """

        response_message = self.llm.invoke([HumanMessage(content=inquiry_response_prompt)])
        email_response = response_message.content

        return {**state, "email_response": email_response}

    def generate_node(self, state: AgentState) -> AgentState:
        """Generate a professional email response based on the order analysis."""

        # Extract information from state
        email_content = state["email_content"]
        order_analysis = state["order_analysis"]
        retrieved_context = self._create_context_from_docs(state["docs"])

        # Analyze the order status
        order_items = order_analysis.get("order_items", [])
        total_items = len(order_items)
        fulfilled_items = [item for item in order_items if item.get("status") == "created"]
        out_of_stock_items = [item for item in order_items if item.get("status") == "out of stock"]

        # Determine response type
        if len(fulfilled_items) == total_items:
            response_type = "fully_processed"
        elif len(fulfilled_items) == 0:
            response_type = "not_fulfilled"
        else:
            response_type = "partially_fulfilled"

        # Create prompt for email response generation
        email_response_prompt = f"""
        Generate a professional email response to a customer's order request based on the analysis below.

        ORIGINAL EMAIL:
        {email_content}

        ORDER ANALYSIS:
        {json.dumps(order_analysis, indent=2)}

        PRODUCT CATALOG CONTEXT:
        {retrieved_context}

        RESPONSE REQUIREMENTS:
        - Use a professional and courteous tone
        - Be production-ready and customer-service oriented
        - Address the customer personally and warmly

        Based on the order status, follow these guidelines:

        {"FULLY PROCESSED ORDER:" if response_type == "fully_processed" else
         "ORDER NOT FULFILLED:" if response_type == "not_fulfilled" else
         "PARTIALLY FULFILLED ORDER:"}

        {'''- Confirm the order has been successfully processed
        - Provide details about each ordered product including name, quantity, and brief description
        - Include next steps (shipping, delivery timeline, order tracking info)
        - Thank the customer for their business''' if response_type == "fully_processed" else

         '''- Apologize for not being able to fulfill the order
        - Clearly specify which items are out of stock
        - Suggest alternatives from the product catalog if available
        - Offer options like waiting for restock, notifications when available, or similar products
        - Maintain a helpful and solution-oriented tone''' if response_type == "not_fulfilled" else

         '''- Acknowledge both fulfilled and unfulfilled parts of the order
        - Confirm details of items that will be processed
        - Clearly explain which specific items are out of stock and why
        - Offer alternatives for out-of-stock items from the product catalog
        - Provide options for the unfulfilled items (wait for restock, notifications, alternatives)
        - Ask if they want to proceed with the partial order'''}

        Generate a complete email response with:
        - Professional subject line
        - Proper greeting
        - Clear explanation of order status
        - Specific product details where relevant
        - Next steps or alternatives
        - Professional closing

        Format the response as a complete email ready to send to the customer.
        """

        # Generate the email response
        email_response_message = self.llm.invoke([
            HumanMessage(content=email_response_prompt)
        ])

        email_response = email_response_message.content

        return {**state, "email_response": email_response}

    def _build_graph(self) -> Runnable:
        # Build graph
        self.config = {'callbacks': [], 'recursion_limit': 10}
        if self.langfuse_handler:
            self.config['callbacks'].append(self.langfuse_handler)

        builder = StateGraph(AgentState)
        builder.add_node("classify_email", RunnableLambda(self.classify_email_node))
        builder.add_node("retrieve", RunnableLambda(self.retrieve_node))
        builder.add_node("agent", RunnableLambda(self.agent_node))
        builder.add_node("tools", ToolNode(self.create_tools()))
        builder.add_node("analyse_order", RunnableLambda(self.analyse_order_node))
        builder.add_node("generate", RunnableLambda(self.generate_node))
        builder.add_node("product_inquiry_response", RunnableLambda(self.product_inquiry_response_node))

        builder.set_entry_point("classify_email")
        builder.add_edge("classify_email", "retrieve")
        builder.add_conditional_edges(
            "retrieve",
            self.should_continue_after_retrieve,
            {
                "agent": "agent",
                "product_inquiry_response": "product_inquiry_response"
            }
        )
        builder.add_conditional_edges(
            "agent",
            self.should_continue,
            {
                "tools": "tools",
                "analyse_order": "analyse_order"
            }
        )
        builder.add_edge("tools", "analyse_order")
        builder.add_edge("analyse_order", "generate")
        builder.add_edge("generate", END)
        builder.add_edge("product_inquiry_response", END)

        self.graph = builder.compile()

    def run(self, email_id: str, email_subject: str, email_message: str) -> dict:
        email_content = f"Subject: {email_subject}\n\nBody: {email_message}"
        return self.graph.invoke({"email_content": email_content, "email_id": email_id}, config=self.config)

{'RSG8901': 1, 'SWL2345': 5, 'VSC6789': 6, 'CSH1098': 3, 'CHN0987': 2, 'LTH0976': 4, 'FZZ1098': 2, 'FRP9876': 3, 'BKR0123': 3, 'CBY6789': 3, 'CLF2109': 2, 'LTG5432': 1, 'CPN3210': 3, 'SFT1098': 8, 'ERM5432': 2, 'VBT2345': 4, 'SBP4567': 6, 'CCB6789': 7, 'CCH6789': 4, 'CBG9876': 1, 'LTH5432': 6, 'LTH1098': 7, 'MSK1098': 8, 'LTH2109': 4, 'QTP5432': 7, 'FRP6789': 2, 'SDE2345': 1, 'DLD0123': 3, 'STT4567': 3, 'CPJ2345': 5, 'LFL7654': 6, 'PTR9876': 1, 'CSW6789': 6, 'DJN8901': 5, 'CPL0123': 7, 'RCS0123': 6, 'TLR5432': 4, 'RGD7654': 5, 'LNS3210': 3, 'CML7654': 2, 'PLV8765': 1, 'PLD9876': 8, 'HNG3210': 6, 'CBL5432': 2, 'BMX2345': 1, 'FLN2345': 2, 'PTN4567': 1, 'PTD8901': 1, 'THK0976': 7, 'HDD9876': 5, 'FNK9876': 4, 'SKR3210': 5, 'RBT0123': 6, 'SLP7654': 4, 'SLD7654': 3, 'CBT8901': 2, 'WTR7654': 6, 'CHL4567': 5, 'FSD2345': 4, 'CCG8901': 4, 'WSK4567': 3, 'FLD9876': 7, 'PTD3210': 5, 'FBL9876': 6, 'CHN5432': 4, 'CRD3210': 5, 'BMX5432': 6, 'KMN3210': 4, 'FLT5678': 8, 'DST6543': 6, 'EMB4321': 7, 'RBB5432': 5, 'CPT1098': 2, 'OVR3210': 6, 'BTN7654': 4, 'CLR1098': 7, 'LTH6789': 2, 'SKT4567': 1, 'DTD0123': 3, 'LGG4567': 2, 'CLR6789': 1, 'VNL8901': 2, 'FZF0123': 2, 'CGN2345': 2, 'PWD6543': 8, 'SWT8765': 6, 'FZV1098': 4, 'QTD5432': 4, 'FLC7654': 7, 'LDR3210': 3, 'WTL1098': 2, 'SCS9876': 3, 'SSN8901': 6, 'MSL1098': 6, 'SND7654': 8, 'CHK8901': 1, 'MLR0123': 2, 'CLG4567': 3, 'SNB4321': 5}

In [37]:
# Instantiating our StockManager using the products_df as stock, the llm and langfuse_handler
stock_count = {item['product_id']: int(item['stock']) for item in products_df.to_records('dict')}
stock_manager = StockManager(stock_count)

llm = ChatOpenAI(
    openai_api_key=OPENAI_API_KEY,
    base_url=OPENAI_BASE,
    model="gpt-4o",
    temperature=0,
)

langfuse_handler = create_langfuse_handler(LANGFUSE_PUBLIC_KEY, LANGFUSE_SECRET_KEY, LANGFUSE_HOST)
agent = OrderAgent(llm, vectorstore, stock_manager, langfuse_handler=langfuse_handler)

emails = [a for a in emails_df.to_records('dict')]
print(emails[0]['email_id'])

analysed_emails = []
for email in emails_df.to_records('dict'):
    response = agent.run(
        email_id=email['email_id'],
        email_subject=email['subject'],
      email_message=email['message']
    )
    analysed_emails.append({
        'email_id': response['email_id'],
        'email_type': response['email_type'],
        'email_response': response['email_response'],
        'order_analysis': response.get('order_analysis'),
    })

E001
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_McyX5VkKvBZmvzGPcrlwqk4x', 'function': {'arguments': '{"product_ids":["LTH0976"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_2Gw9hfs3MhJuKBU7JppATx3M', 'function': {'arguments': '{"product_ids":["VBT2345"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT

Product ID: LTH1098
Name: Leather Backpack
Category: Bags
Seasons: All seasons
Description: Upgrade your daily carry with our leather backpack. Crafted from premium leather, this stylish backpack features multiple compartments, a padded laptop sleeve, and adjustable straps for a comfortable fit. Perfect for work, travel, or everyday use.
Price: 43.99
---

Product ID: LTH5432
Name: Leather Tote
Category: Bags
Seasons: All seasons
Description: Elevate your everyday carry with our leather tote bag. Crafted from premium, full-grain leather, this bag features a spacious interior, multiple pockets, and sturdy handles. Perfect for work, travel, or running errands in style.
Price: 28.0
---

Product ID: SBP4567
Name: Sleek Backpack
Category: Bags
Seasons: All seasons
Description: Streamline your daily carry with our sleek backpack. Designed for both style and functionality, this bag features multiple compartments to keep your essentials organized and a padded laptop sleeve for added protection.
Price: 29.99
---

Product ID: QTP5432
Name: Quilted Tote
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our quilted tote bag. This spacious bag features a classic quilted design, multiple interior pockets, and sturdy handles. A chic and practical choice for work, travel, or everyday use. Limited-time sale - get 25% off!
Price: 29.0
---

Product ID: LTH2109
Name: Leather Messenger Bag
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our leather messenger bag. Crafted from premium, full-grain leather, this bag features a spacious main compartment, multiple pockets, and an adjustable strap for a comfortable fit. A timeless choice for work, travel, or everyday use.
Price: 37.99
---
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_XksAwRJ3s4d0YdOZXnKbVSaj', 'function': {'arguments': '{"product_ids":["SFT1098"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT

Product ID: CSH1098
Name: Cozy Shawl
Category: Accessories
Seasons: Fall, Winter
Description: Wrap yourself in comfort with our cozy shawl. Knitted from soft, warm yarn, this versatile accessory can be worn as a shawl, scarf, or even a lightweight blanket. Perfect for chilly evenings or adding a cozy layer to your outfit.
Price: 22.0
---

Product ID: VSC6789
Name: Versatile Scarf
Category: Accessories
Seasons: Spring, Fall
Description: Add a touch of versatility to your wardrobe with our versatile scarf. This lightweight, multi-purpose accessory can be worn as a scarf, shawl, or even a headwrap. Perfect for transitional seasons or travel.
Price: 23.0
---

Product ID: CPN3210
Name: Cashmere Poncho
Category: Accessories
Seasons: Winter
Description: Wrap yourself in luxury with our cashmere poncho. Knitted from premium cashmere yarn, this ultra-soft poncho offers a cozy, enveloping warmth. A stylish and versatile layering piece for chilly winter days.
Price: 48.0
---

Product ID: SFT1098
Name: Infinity Scarf
Category: Accessories
Seasons: Winter
Description: Stay cozy and stylish with our infinity scarf. This versatile accessory features a soft, chunky knit construction and an endless loop design for easy wearing. Perfect for adding a touch of warmth and texture to your winter ensembles.
Price: 28.0
---

Product ID: CCG8901
Name: Cozy Cardigan
Category: Women's Clothing
Seasons: Fall, Winter, Spring
Description: Layer up in style with our cozy cardigan. Crafted from soft, warm materials, this versatile piece can be dressed up or down. Perfect for chilly days or chilly office spaces.
Price: 61.99
---

Product ID: CBT8901
Name: Chelsea Boots
Category: Men's Shoes
Seasons: Fall, Winter
Description: Elevate your casual looks with our Chelsea boots. These stylish ankle boots feature a sleek leather construction, elastic side panels, and a sturdy lug sole. An essential for completing modern, edgy outfits.
Price: 65.0
---

Product ID: CHK8901
Name: Chunky Sneakers
Category: Women's Shoes
Seasons: Spring, Fall
Description: Step into trendy style with our chunky sneakers. These statement sneakers feature a bold, chunky sole and a sleek leather or knit upper. A must-have for fashion-savvy individuals who appreciate both style and comfort. Only a few pairs left!
Price: 42.0
---

Product ID: SNB4321
Name: Snow Boots
Category: Women's Shoes
Seasons: Winter
Description: Brave the elements in our durable snow boots. These waterproof boots feature a rugged, lug sole for traction, a cozy fleece lining, and a water-resistant outer shell. A must-have for outdoor adventures or navigating snowy conditions.
Price: 41.0
---

Product ID: WTR7654
Name: Waterproof Boots
Category: Men's Shoes
Seasons: Winter
Description: Stay dry and comfortable in our waterproof boots. These durable boots feature a water-resistant outer shell, a cozy fleece lining, and a rugged, lug sole for traction. An essential for navigating snowy or rainy conditions.
Price: 51.0
---

Product ID: RBT0123
Name: Rugged Boots
Category: Men's Shoes
Seasons: Fall, Winter
Description: Tackle any terrain with our rugged boots. Crafted from durable materials and featuring a sturdy sole, these boots offer both style and functionality. Perfect for outdoor adventures or city explorations.
Price: 39.0
---
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_XNgCNEe6lkaeGY78GvNSbmlv', 'function': {'arguments': '{"product_ids":["CLF2109","FZZ1098"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_Jm1xXiSTqXnf4l9HjYW1E1zV', 'function': {'arguments': '{"product_ids":["VSC6789"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT

Product ID: CHN0987
Name: Chunky Knit Beanie
Category: Accessories
Seasons: Fall, Winter
Description: Keep your head toasty with our chunky knit beanie. Knitted from thick, cozy yarn, this trendy beanie offers a slouchy, oversized fit and a touch of rustic charm. A versatile accessory to elevate your cold-weather looks.
Price: 22.0
---

Product ID: CLF2109
Name: Cable Knit Beanie
Category: Accessories
Seasons: Winter
Description: Bundle up in our cable knit beanie. Knitted from premium wool, this classic beanie features a timeless cable knit pattern and a soft, stretchy fit. A versatile accessory for adding a touch of warmth and texture to your cold-weather looks.
Price: 16.0
---

Product ID: SFT1098
Name: Infinity Scarf
Category: Accessories
Seasons: Winter
Description: Stay cozy and stylish with our infinity scarf. This versatile accessory features a soft, chunky knit construction and an endless loop design for easy wearing. Perfect for adding a touch of warmth and texture to your winter ensembles.
Price: 28.0
---

Product ID: CHN5432
Name: Chunky Knit Sweater
Category: Women's Clothing
Seasons: Fall, Winter
Description: Stay cozy and stylish with our chunky knit sweater. Crafted from soft, high-quality yarn, this oversized sweater features a trendy, chunky knit pattern and a relaxed fit. Perfect for layering or wearing on its own.
Price: 79.99
---

Product ID: CSW6789
Name: Cozy Sweater
Category: Men's Clothing
Seasons: Fall, Winter
Description: Stay warm and stylish with our cozy sweater. Crafted from soft, high-quality materials, this sweater is perfect for layering or wearing on its own. The classic design makes it a wardrobe staple.
Price: 48.0
---
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_JiU77gX7kKjeSyQyLT4vjZ20', 'function': {'arguments': '{"product_ids":["RSG8901"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT

Product ID: RSG8901
Name: Retro Sunglasses
Category: Accessories
Seasons: Spring, Summer
Description: Transport yourself back in time with our retro sunglasses. These vintage-inspired shades offer a cool, nostalgic vibe while protecting your eyes from the sun's rays. Perfect for beach days or city strolls.
Price: 26.99
---

Product ID: SDE2345
Name: Saddle Bag
Category: Bags
Seasons: All seasons
Description: Channel vintage charm with our saddle bag. This compact crossbody features a classic saddle shape and a trendy, minimalist design. Perfect for adding a touch of retro flair to any ensemble. Limited stock available!
Price: 39.0
---

Product ID: CLG4567
Name: Clog Sandals
Category: Women's Shoes
Seasons: Spring, Summer
Description: Step into retro-inspired style with our clog sandals. These open-toe sandals feature a classic clog silhouette and a sturdy, wooden sole. A trendy and comfortable choice for casual outings or weekend wear.
Price: 48.0
---

Product ID: CRD3210
Name: Corduroy Pants
Category: Women's Clothing
Seasons: Fall, Winter
Description: Embrace the retro trend with our corduroy pants. Crafted from soft, textured corduroy, these high-waisted pants offer a flattering fit and a touch of vintage charm. Dress them up with a blouse or keep it casual with a tee.
Price: 65.0
---

Product ID: BTN7654
Name: Button-Front Skirt
Category: Women's Clothing
Seasons: Spring, Summer, Fall
Description: Add a touch of retro charm to your look with our button-front skirt. This midi-length skirt features a flattering A-line silhouette and a row of buttons down the front. A versatile choice for dressing up or down.
Price: 71.99
---

Product ID: LTH2109
Name: Leather Messenger Bag
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our leather messenger bag. Crafted from premium, full-grain leather, this bag features a spacious main compartment, multiple pockets, and an adjustable strap for a comfortable fit. A timeless choice for work, travel, or everyday use.
Price: 37.99
---

Product ID: LTH1098
Name: Leather Backpack
Category: Bags
Seasons: All seasons
Description: Upgrade your daily carry with our leather backpack. Crafted from premium leather, this stylish backpack features multiple compartments, a padded laptop sleeve, and adjustable straps for a comfortable fit. Perfect for work, travel, or everyday use.
Price: 43.99
---

Product ID: LTH5432
Name: Leather Tote
Category: Bags
Seasons: All seasons
Description: Elevate your everyday carry with our leather tote bag. Crafted from premium, full-grain leather, this bag features a spacious interior, multiple pockets, and sturdy handles. Perfect for work, travel, or running errands in style.
Price: 28.0
---

Product ID: QTP5432
Name: Quilted Tote
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our quilted tote bag. This spacious bag features a classic quilted design, multiple interior pockets, and sturdy handles. A chic and practical choice for work, travel, or everyday use. Limited-time sale - get 25% off!
Price: 29.0
---

Product ID: CCB6789
Name: Chic Crossbody
Category: Bags
Seasons: All seasons
Description: Keep your essentials close with our chic crossbody bag. Compact yet spacious, this stylish bag features multiple compartments and adjustable straps for a comfortable carry. Perfect for everyday use or travel.
Price: 35.0
---

WARNING:opentelemetry.exporter.otlp.proto.http.trace_exporter:Transient error Bad Gateway encountered while exporting span batch, retrying in 1.05s.
WARNING:opentelemetry.exporter.otlp.proto.http.trace_exporter:Transient error Bad Gateway encountered while exporting span batch, retrying in 1.97s.

Calling LLM with 1 tools bound

ERROR:opentelemetry.exporter.otlp.proto.http.trace_exporter:Failed to export span batch code: 502, reason: <!DOCTYPE html>
<!--[if lt IE 7]> <html class="no-js ie6 oldie" lang="en-US"> <![endif]-->
<!--[if IE 7]>    <html class="no-js ie7 oldie" lang="en-US"> <![endif]-->
<!--[if IE 8]>    <html class="no-js ie8 oldie" lang="en-US"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en-US"> <!--<![endif]-->
<head>


<title>cloud.langfuse.com | 502: Bad gateway</title>
<meta charset="UTF-8" />
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=Edge" />
<meta name="robots" content="noindex, nofollow" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />


</head>
<body>
<div id="cf-wrapper">
    <div id="cf-error-details" class="p-0">
        <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-8">
            <h1 class="inline-block sm:block sm:mb-2 font-light text-60 lg:text-4xl text-black-dark leading-tight mr-2">
              <span class="inline-block">Bad gateway</span>
              <span class="code-label">Error code 502</span>
            </h1>
            <div>
               Visit <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=cloud.langfuse.com" target="_blank" rel="noopener noreferrer">cloudflare.com</a> for more information.
            </div>
            <div class="mt-3">2025-07-27 13:51:45 UTC</div>
        </header>
        <div class="my-8 bg-gradient-gray">
            <div class="w-240 lg:w-full mx-auto">
                <div class="clearfix md:px-8">

<div id="cf-browser-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-browser block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">You</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Browser

  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-cloudflare-status" class=" relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=cloud.langfuse.com" target="_blank" rel="noopener noreferrer">
    <span class="cf-icon-cloud block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-ok w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>
    </a>
  </div>
  <span class="md:block w-full truncate">Seattle</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">
    <a href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=cloud.langfuse.com" target="_blank" rel="noopener noreferrer">
    Cloudflare
    </a>
  </h3>
  <span class="leading-1.3 text-2xl text-green-success">Working</span>
</div>

<div id="cf-host-status" class="cf-error-source relative w-1/3 md:w-full py-15 md:p-0 md:py-8 md:text-left md:border-solid md:border-0 md:border-b md:border-gray-400 overflow-hidden float-left md:float-none text-center">
  <div class="relative mb-10 md:m-0">

    <span class="cf-icon-server block md:hidden h-20 bg-center bg-no-repeat"></span>
    <span class="cf-icon-error w-12 h-12 absolute left-1/2 md:left-auto md:right-0 md:top-0 -ml-6 -bottom-4"></span>

  </div>
  <span class="md:block w-full truncate">cloud.langfuse.com</span>
  <h3 class="md:inline-block mt-3 md:mt-0 text-2xl text-gray-600 font-light leading-1.3">

    Host

  </h3>
  <span class="leading-1.3 text-2xl text-red-error">Error</span>
</div>

                </div>
            </div>
        </div>

        <div class="w-240 lg:w-full mx-auto mb-8 lg:px-8">
            <div class="clearfix">
                <div class="w-1/2 md:w-full float-left pr-6 md:pb-10 md:pr-0 leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What happened?</h2>
                    <p>The web server reported a bad gateway error.</p>
                </div>
                <div class="w-1/2 md:w-full float-left leading-relaxed">
                    <h2 class="text-3xl font-normal leading-1.3 mb-4">What can I do?</h2>
                    <p class="mb-6">Please try again in a few minutes.</p>
                </div>
            </div>
        </div>

        <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">
  <p class="text-13">
    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">965c9d05eabeba22</strong></span>
    <span class="cf-footer-separator sm:hidden">&bull;</span>
    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">
      Your IP:
      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>
      <span class="hidden" id="cf-footer-ip">34.168.163.25</span>
      <span class="cf-footer-separator sm:hidden">&bull;</span>
    </span>
    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing?utm_source=errorcode_502&utm_campaign=cloud.langfuse.com" id="brand_link" target="_blank">Cloudflare</a></span>

  </p>
  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>
</div><!-- /.error-footer -->


    </div>
</div>
</body>
</html>

LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_JeOKHKR5wTnbeMqiNvNQ61yn', 'function': {'arguments': '{"product_ids":["SLD7654"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_cixVPbQtGDa3aiOVPOxHQ8xI', 'function': {'arguments': '{"product_ids":["SWL2345"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT

Product ID: LTH2109
Name: Leather Messenger Bag
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our leather messenger bag. Crafted from premium, full-grain leather, this bag features a spacious main compartment, multiple pockets, and an adjustable strap for a comfortable fit. A timeless choice for work, travel, or everyday use.
Price: 37.99
---

Product ID: LTH5432
Name: Leather Tote
Category: Bags
Seasons: All seasons
Description: Elevate your everyday carry with our leather tote bag. Crafted from premium, full-grain leather, this bag features a spacious interior, multiple pockets, and sturdy handles. Perfect for work, travel, or running errands in style.
Price: 28.0
---

Product ID: LTH1098
Name: Leather Backpack
Category: Bags
Seasons: All seasons
Description: Upgrade your daily carry with our leather backpack. Crafted from premium leather, this stylish backpack features multiple compartments, a padded laptop sleeve, and adjustable straps for a comfortable fit. Perfect for work, travel, or everyday use.
Price: 43.99
---

Product ID: QTP5432
Name: Quilted Tote
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our quilted tote bag. This spacious bag features a classic quilted design, multiple interior pockets, and sturdy handles. A chic and practical choice for work, travel, or everyday use. Limited-time sale - get 25% off!
Price: 29.0
---

Product ID: SBP4567
Name: Sleek Backpack
Category: Bags
Seasons: All seasons
Description: Streamline your daily carry with our sleek backpack. Designed for both style and functionality, this bag features multiple compartments to keep your essentials organized and a padded laptop sleeve for added protection.
Price: 29.99
---

Product ID: FSD2345
Name: Floral Sundress
Category: Women's Clothing
Seasons: Spring, Summer
Description: Embrace the warm weather in our floral sundress. This breezy, lightweight dress features a vibrant floral print and a flattering silhouette. Perfect for sunny days or tropical vacations.
Price: 58.0
---

Product ID: FLD9876
Name: Floral Maxi Dress
Category: Women's Clothing
Seasons: Spring, Summer
Description: Embrace the blooming season with our floral maxi dress. This breezy, lightweight dress features a vibrant floral pattern and a flattering silhouette that flows gracefully with every step. Perfect for garden parties, beach vacations, or romantic evenings. Act now and get 20% off!
Price: 56.0
---

Product ID: SND7654
Name: Strappy Sandals
Category: Women's Shoes
Seasons: Spring, Summer
Description: Step into summer with our strappy sandals. These open-toe sandals feature a trendy, strappy design and a comfortable, cushioned footbed. Perfect for beach days, outdoor events, or casual weekend wear.
Price: 27.0
---

Product ID: FLT5678
Name: Flowy Linen Top
Category: Women's Clothing
Seasons: Spring, Summer
Description: Embrace effortless style with our flowy linen top. Crafted from airy, breathable linen, this relaxed top features a flattering drape and a chic, minimalist design. An ideal choice for warm weather or layering during transitional seasons.
Price: 41.0
---

Product ID: PTD3210
Name: Printed Tunic Dress
Category: Women's Clothing
Seasons: Spring, Summer
Description: Stand out from the crowd with our printed tunic dress. This vibrant, eye-catching dress features a bold print and a flattering, relaxed silhouette. Perfect for running errands, casual outings, or a weekend brunch with friends.
Price: 67.99
---
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_ATDsyXGHCasmPuPIPAjykClA', 'function': {'arguments': '{"product_ids":["CHK8901"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_E9SO2s8BHd3yU7frHwt5mlPV', 'function': {'arguments': '{"product_ids":["RSG8901"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_nEdAaKWedkCSQerKIEmbkxPB', 'function': {'arguments': '{"product_ids":["CBT8901","FZZ1098"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT

Product ID: SDE2345
Name: Saddle Bag
Category: Bags
Seasons: All seasons
Description: Channel vintage charm with our saddle bag. This compact crossbody features a classic saddle shape and a trendy, minimalist design. Perfect for adding a touch of retro flair to any ensemble. Limited stock available!
Price: 39.0
---

Product ID: FRP6789
Name: Fringe Crossbody
Category: Bags
Seasons: Spring, Summer, Fall
Description: Embrace boho-chic style with our fringe crossbody bag. This compact bag features a fringed exterior and a stylish saddle shape. Perfect for adding a touch of free-spirited flair to any outfit.
Price: 67.0
---

Product ID: LTH2109
Name: Leather Messenger Bag
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our leather messenger bag. Crafted from premium, full-grain leather, this bag features a spacious main compartment, multiple pockets, and an adjustable strap for a comfortable fit. A timeless choice for work, travel, or everyday use.
Price: 37.99
---

Product ID: QTP5432
Name: Quilted Tote
Category: Bags
Seasons: All seasons
Description: Carry your essentials in style with our quilted tote bag. This spacious bag features a classic quilted design, multiple interior pockets, and sturdy handles. A chic and practical choice for work, travel, or everyday use. Limited-time sale - get 25% off!
Price: 29.0
---

Product ID: CCB6789
Name: Chic Crossbody
Category: Bags
Seasons: All seasons
Description: Keep your essentials close with our chic crossbody bag. Compact yet spacious, this stylish bag features multiple compartments and adjustable straps for a comfortable carry. Perfect for everyday use or travel.
Price: 35.0
---

Product ID: CHN0987
Name: Chunky Knit Beanie
Category: Accessories
Seasons: Fall, Winter
Description: Keep your head toasty with our chunky knit beanie. Knitted from thick, cozy yarn, this trendy beanie offers a slouchy, oversized fit and a touch of rustic charm. A versatile accessory to elevate your cold-weather looks.
Price: 22.0
---

Product ID: ERM5432
Name: Earmuffs
Category: Accessories
Seasons: Winter
Description: Keep your ears toasty with our earmuffs. These plush earmuffs feature a soft, faux fur exterior and an adjustable headband for a secure fit. A practical and stylish accessory for braving the cold in comfort.
Price: 23.0
---

Product ID: CBY6789
Name: Corduroy Bucket Hat
Category: Accessories
Seasons: Fall, Winter
Description: Keep it casual and cool with our corduroy bucket hat. This trendy hat features a soft corduroy construction and a relaxed, bucket silhouette. A must-have accessory for achieving a laidback, streetwear-inspired look.
Price: 28.0
---

Product ID: CLF2109
Name: Cable Knit Beanie
Category: Accessories
Seasons: Winter
Description: Bundle up in our cable knit beanie. Knitted from premium wool, this classic beanie features a timeless cable knit pattern and a soft, stretchy fit. A versatile accessory for adding a touch of warmth and texture to your cold-weather looks.
Price: 16.0
---

Product ID: BKR0123
Name: Bucket Hat
Category: Accessories
Seasons: Spring, Summer
Description: Protect your face from the sun in style with our trendy bucket hat. This casual hat features a cotton construction and a wide, floppy brim. A must-have accessory for beach days, music festivals, or adding a touch of streetwear flair.
Price: 39.99
---
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_UhKbY9Ttof4yr3vsGusVrGEJ', 'function': {'arguments': '{"product_ids":["VBT2345"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT
Calling LLM with 1 tools bound
LLM Response type: <class 'langchain_core.messages.ai.AIMessage'>
Last message type: <class 'langchain_core.messages.ai.AIMessage'>
Last message content:
Last message additional_kwargs: {'tool_calls': [{'id': 'call_DnutEBelHCKPHPrHfcp9hfpX', 'function': {'arguments': '{"product_ids":["CGN2345"]}', 'name': 'get_stock_count'}, 'type': 'function'}], 'refusal': None}
Found tool_calls, going to tools
RETURNING STOCK COUNT

In [35]:
%pip install ipdb

Collecting ipdb
  Downloading ipdb-0.13.13-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: ipython>=7.31.1 in /usr/local/lib/python3.11/dist-packages (from ipdb) (7.34.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.11/dist-packages (from ipdb) (4.4.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (75.2.0)
Collecting jedi>=0.16 (from ipython>=7.31.1->ipdb)
  Downloading jedi-0.19.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (3.0.51)
Requirement already satisfied: pygments in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (2.19.2)
Requirement already satisfied: backcall in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.11/dist-packages (from ipython>=7.31.1->ipdb) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.11/dist-packages (from jedi>=0.16->ipython>=7.31.1->ipdb) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.11/dist-packages (from pexpect>4.3->ipython>=7.31.1->ipdb) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.11/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=7.31.1->ipdb) (0.2.13)
Downloading ipdb-0.13.13-py3-none-any.whl (12 kB)
Downloading jedi-0.19.2-py2.py3-none-any.whl (1.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.8 MB/s eta 0:00:00
Installing collected packages: jedi, ipdb
Successfully installed ipdb-0.13.13 jedi-0.19.2

In [47]:
# Write email classification, order statuses and email responses to the sheet
for i, email in enumerate(analysed_emails, start=2):
    email_classification_sheet.update([[email['email_id'], email['email_type']]], f"A{i}:B{i}")
    if email['order_analysis']:
        for order_item in email['order_analysis']['order_items']:
            next_order_status_row = len(order_status_sheet.col_values(1)) + 1
            order_status_sheet.update(
                [[email['email_id'], order_item['product_id'], order_item['order_quantity'], order_item['status']]],
                f'A{next_order_status_row}:D{next_order_status_row}'
            )

    response_sheet = order_response_sheet if email['email_type'] == 'order request' else inquiry_response_sheet
    next_resonse_row = len(response_sheet.col_values(1)) + 1
    response_sheet.update([[email['email_id'], email['email_response']]], f'A{next_resonse_row}:B{next_resonse_row}')

# Task 1. Classify emails

# Task 2. Process order requests

# Task 3. Handle product inquiry